#ENV: PRODUCTION
ENV: DEVELOPMENT
VERSION: 1.0
DEFAULT:
  ALLOWED_HOSTS:
    - "*"
  HOST: "0.0.0.0"
  PORT: 9021

DEVELOPMENT:
  LOGGING:
    LOGGING_LEVEL: DEBUG
    LOGGING_FORMAT: "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"

PRODUCTION:
  LOGGING:
    LOGGING_LEVEL: INFO
    LOGGING_FORMAT: "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"

AWS:
  AWS_REGION: "us-east-1"
  AWS_SECRET_NAME: "resume_parsing_wrapper"
